### ISSUE TITLE
Website root links

### ISSUE THREAD

**Issue by danboh** [nasirkhan/laravel-5-starter-application#1]
Hi, thank you for this.

I'm trying Laravel 5 for the first time, and this great so far. Just one thing though, the links in the Login page in the form of /auth/login point to a location outside of the website root. Instead I've had to replace them with {!! link_to('auth/login') !!}

Could it be something I'm missing in my configuration?

Thanks.

**Comment by nasirkhan** [comment]
thanks for mentioning the issue. 
Are you using Virtualhost on your local machine? If not i recommend you to use explore this. If you point your virtual domain to the public directory you will not face this issue. 

Apart form this the path should not be written as such. I will add the route name on all the forms.

**Comment by danboh** [comment]
I'm using Virtualhost on a Bitnami LAMP server. I will see about pointing it to the public directory.

I tried logging in with Facebook, but after creating the APP_ID and APP_SECRET it doesn't seem like the user is created in the DB nor the callback seem to functioning properly because the menu doesn't change. Any thoughts?

**Comment by danboh** [comment]
Never mind, figured it out. Thanks
