### ISSUE TITLE
Images folder

### ISSUE THREAD

**Issue by danboh** [nasirkhan/laravel-5-starter-application#3]
Hi again,

There's no images folder under the public directory, but when created, and when trying to access an image within the folder like: **http://mysite.com/images/logo.png** I get an **NotFoundHttpException**.

Tried  checking the .htaccess file but couldn't figure it out.

Any thoughts?

Thanks again!

**Comment by nasirkhan** [comment]
Thank you for your interest. This project is not maintained now please check the other updated project where you will find all of these feature and more. https://github.com/nasirkhan
